### ISSUE TITLE
Container registry settings have no effect

### ISSUE THREAD

**Issue by saitho** [getstackhead/module-container-docker#14]
The private registry login date set via

```
container:
  registries:
    - username: foo
      password: bar
```

is not applied. The Terraform provider file is evalated during the setup.
However the registry data is set during project deployment.
